routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::get('/files', 'FileController@index')->name('files.index');
Route::get('/files/{id}/download', 'FileController@download')->name('files.download');
Route::get('/files/{id}/play', 'FileController@play')->name('files.play');
Auth::routes();

app/File.php
<?php

namespace App;

use App\IPFS;
use Illuminate\Database\Eloquent\Model;
use Storage;

class File extends Model
{
    protected $fillable = ['name', 'filename', 'ipfs_hash'];
    protected $table = 'files';

    public function download()
    {
        $ipfs = new IPFS();
        Storage::put($this->full_path, $ipfs->get($this->ipfs_hash));
    }

    public function exists()
    {
        return Storage::exists($this->full_path);
    }

    public function filesDownloading()
    {
    	return $this->hasMany('App\FilesDownloading', 'file_id');
    }

    public function filesize()
    {
        if ($this->exists())
        {
            return Storage::size($this->full_path) > 0;
        }

        return false;
    }

    public function filetype()
    {
    	return $this->belongsTo('App\Filetype', 'filetype_id');
    }

    public function folder()
    {
    	return $this->belongsTo('App\Folder', 'folder_id');
    }

    public function getFullPathAttribute()
    {
        if ($this->folder)
        {
            return $this->folder->full_path.'/'.$this->filename;
        }
        return $this->filename;
    }

    public function getWebPathAttribute()
    {
        return '/storage/ipfs/'.$this->full_path;
    }

    public function hashes()
    {
    	return $this->hasMany('App\Hash', 'file_id');
    }

    public function isDownloaded()
    {
        return $this->filesize() > 0;
    }

    public function thumbnailFile()
    {
    	return $this->hasMany('App\File', 'thumbnail_file_id');
    }

    public function verify()
    {
        if (!$this->isDownloaded())
        {
            return false;
        }

        foreach ($this->hashes as $hash)
        {
            if (!$hash->verify())
            {
                return false;
            }
        }

        return true;
    }
}

app/Filetype.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Filetype extends Model
{
    protected $table = 'filetypes';

    public function files()
    {
    	return $this->belongsTo('App\File', 'filetype_id');
    }
}

app/Folder.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Folder extends Model
{
    protected $table = 'folders';

    public function children()
    {
    	return $this->hasMany('App\Folder', 'parent_id');
    }

    public function getFullPathAttribute()
    {
        if ($this->parent)
        {
            return $this->parent->full_path.'/'.$name;
        }

        return $this->name;
    }

    public function files()
    {
    	return $this->hasMany('App\File', 'folder_id');
    }

    public function parent()
    {
    	return $this->belongsTo('App\Folder', 'parent_id');
    }
}

app/Hash.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Hash extends Model
{
    protected $table = 'hashes';

    public function file()
    {
    	return $this->belongsTo('App\File', 'file_id');
    }

    public function verifications()
    {
    	return $this->hasMany('App\HashVerification', 'hash_id');
    }

    public function verify()
    {
    	//TODO: This
    	return true;
    }
}

app/HashVerification.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class HashVerification extends Model
{
    protected $table = 'hashes_verifications';

    public function file()
    {
    	return $this->belongsTo('App\File', 'file_id');
    }

    public function hash()
    {
    	return $this->belongsTo('App\Hash', 'hash_id');
    }
}

app/IPFS.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class IPFS {
	private $gatewayIP;
	private $gatewayPort;
	private $gatewayApiPort;

	function __construct($ip = "localhost", $port = "8080", $apiPort = "5001") {
		$this->gatewayIP      = $ip;
		$this->gatewayPort    = $port;
		$this->gatewayApiPort = $apiPort;
	}

	public function cat ($hash) {
		$ip = $this->gatewayIP;
		$port = $this->gatewayPort;
		return $this->curl("http://$ip:$port/ipfs/$hash"); 

	}

	public function get($hash, $folder = '')
	{
		$ip = $this->gatewayIP;
		$port = $this->gatewayApiPort;
		return $this->curl("http://$ip:$port/api/v0/get?arg=$hash&output=$folder"); 
	}

	public function add ($content) {
		$ip = $this->gatewayIP;
		$port = $this->gatewayApiPort;

		$req = $this->curl("http://$ip:$port/api/v0/add?stream-channels=true", $content);
		$req = json_decode($req, TRUE);

		return $req['Hash'];
	}

	public function ls ($hash) {
		$ip = $this->gatewayIP;
		$port = $this->gatewayApiPort;

		$response = $this->curl("http://$ip:$port/api/v0/ls/$hash");

		$data = json_decode($response, TRUE);

		return $data['Objects'][0]['Links'];
	}

	public function size ($hash) {
		$ip = $this->gatewayIP;
		$port = $this->gatewayApiPort;

		$response = $this->curl("http://$ip:$port/api/v0/object/stat/$hash");
		$data = json_decode($response, TRUE);

		return $data['CumulativeSize'];
	}

	public function pinAdd ($hash) {
		
		$ip = $this->gatewayIP;
		$port = $this->gatewayApiPort;

		$response = $this->curl("http://$ip:$port/api/v0/pin/add/$hash");
		$data = json_decode($response, TRUE);

		return $data;
	}
	
	public function pinRm ($hash) {
		
		$ip = $this->gatewayIP;
		$port = $this->gatewayApiPort;

		$response = $this->curl("http://$ip:$port/api/v0/pin/rm/$hash");
		$data = json_decode($response, TRUE);

		return $data;
	}
	
	public function version () {
		
		$ip = $this->gatewayIP;
		$port = $this->gatewayApiPort;

		$response = $this->curl("http://$ip:$port/api/v0/version");
		$data = json_decode($response, TRUE);

		return $data['Version'];
	}
	
	public function id () {
		
		$ip = $this->gatewayIP;
		$port = $this->gatewayApiPort;

		$response = $this->curl("http://$ip:$port/api/v0/id");
		$data = json_decode($response, TRUE);

		return $data;
	}

	private function curl ($url, $data = "") {
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, $url);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_TIMEOUT, 5);
		curl_setopt($ch, CURLOPT_HEADER, 0);
		curl_setopt($ch, CURLOPT_BINARYTRANSFER,1);
		 
		if ($data != "") {
			curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: multipart/form-data; boundary=a831rwxi1a3gzaorw1w2z49dlsor')); 
			curl_setopt($ch, CURLOPT_POST, 1);
			curl_setopt($ch, CURLOPT_POSTFIELDS, "--a831rwxi1a3gzaorw1w2z49dlsor\r\nContent-Type: application/octet-stream\r\nContent-Disposition: file; \r\n\r\n" . $data . "\r\n--a831rwxi1a3gzaorw1w2z49dlsor");
		}

		$output = curl_exec($ch);

		if ($output == FALSE) {
			//todo: when ipfs doesn't answer
		}		 
		curl_close($ch);
 

		return $output;
	}
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FileController.php
<?php

namespace App\Http\Controllers;

use App\File;
use Illuminate\Http\Request;

class FileController extends Controller
{
	public function download($id)
	{
		$file = File::find($id);
		$file->download();

		return redirect()->route('files.index');
	}

    public function index()
    {
    	$files = File::all();
    	return view('files.index', ['files' => $files]);
    }

    public function play($id)
    {
    	$file = File::find($id);

    	return view('files.play', ['file' => $file]);
    }
}

resources/views/files/index.blade.php
@extends('template')

@section('content')
	@foreach ($files as $file)
	<p><a href="{{ route('files.download', $file->id) }}">{{ $file->name }}</a> - <a href="{{ route('files.play', $file->id) }}">Play</a></p>
	@endforeach
@endsection

resources/views/files/play.blade.php
@extends('template')

@section('css')
<link href="/css/player.css" rel="stylesheet">
@endsection

@section('content')
	<h1>Play {{ $file->name }}</h1>
	@if ($file->isDownloaded())
		<p>File is downloaded successfully <b>{{ $file->web_path }}</b>. Play below.</p>
		<h2 class="title">Single Song</h2>
		<div class="row">
			<div class="col-12">
				<div id="single-song-player">
					<img amplitude-song-info="cover_art_url" amplitude-main-song-info="true" />
					<div class="bottom-container">
						<progress class="amplitude-song-played-progress" amplitude-main-song-played-progress="true" id="song-played-progress"></progress>
						<div class="time-container">
							<span class="current-time">
							<span class="amplitude-current-minutes" amplitude-main-current-minutes="true"></span>:<span class="amplitude-current-seconds" amplitude-main-current-seconds="true"></span>
							</span>
							<span class="duration">
							<span class="amplitude-duration-minutes" amplitude-main-duration-minutes="true"></span>:<span class="amplitude-duration-seconds" amplitude-main-duration-seconds="true"></span>
							</span>
						</div>
						<div class="control-container">
							<div class="amplitude-play-pause" amplitude-main-play-pause="true" id="play-pause"></div>
							<div class="meta-container">
								<span amplitude-song-info="name" amplitude-main-song-info="true" class="song-name"></span>
								<span amplitude-song-info="artist" amplitude-main-song-info="true"></span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	@elseif ($file->exists())
		<p>This file is downloaded, but there is an error - this is most likely caused by the fact that the IPFS daemon isn't running. </p>
	@else
		<p>File is not downloaded. Please <a href="{{ route('files.download', $file->id) }}">click here</a> to download. </p>
	@endif
@endsection

@section('javascript')
<script src="https://cdnjs.cloudflare.com/ajax/libs/amplitudejs/3.3.1/amplitude.min.js"></script>
<script>
Amplitude.init({
	"songs": [
		{
			"name": "Song Name 1",
			"artist": "Artist Name",
			"album": "Album Name",
			"url": "{{ $file->web_path }}",
			"cover_art_url": "/cover/art/url.jpg"
		}
	]
});
</script>
@endsection

resources/views/home.blade.php
@extends('template')

@section('content')
<div class="row">
    <div class="col-12">
        <h1>Andach IPFS</h1>

        <p>This is a small home server project to create an IPFS GUI.</p>
    </div>
</div>
@endsection

resources/views/template.blade.php
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Andach IPFS</title>

    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
    @yield('css')

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
      <div class="container">
        <a class="navbar-brand" href="/">Andach IPFS</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('files.index') }}">Files</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    @if (Session::has('success'))
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="alert alert-success"><b>Success:</b> {!! Session::get('success') !!}</div>
        </div>
      </div>
    </div>
    @endif


    <!-- Page Content -->
    <div class="container">
      @yield('content')
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    @yield('javascript')

  </body>

</html>